dataset_config:
  hateful_memes:
    processors:
      image_processor: # Additional Parameters
        type: torchvision_transforms
        params:
          transforms:
            - type: Resize
              params:
                size: [256, 256]
            - type: CenterCrop
              params:
                size: [224, 224]