includes:
- configs/datasets/hateful_memes/bert.yaml
- ./image_preprocessors.yaml

model_config:
  late_fusion:
    text_encoder:
      type: transformer
      params:
        hidden_size: 768
        num_hidden_layers: 12
        num_attention_heads: 12
        output_attentions: true
        output_hidden_states: false
    modal_classifier:
      type: mlp
      params:
        num_layers: 2
    text_classifier:
      type: mlp
      params:
        num_layers: 2
    losses:
    - type: cross_entropy

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 2000
    num_training_steps: ${training.max_updates}

optimizer:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

evaluation:
  metrics:
  - accuracy
  - binary_f1
  - roc_auc

training:
  batch_size: 1
  lr_scheduler: true
  max_updates: 22000
  max_epochs: 10
  early_stop:
    criteria: hateful_memes/roc_auc
    minimize: false

checkpoint:
  pretrained_state_mapping:
    base: base
